// Katalog ma'lumotlari va ikki tildagi matnlar (UZ — lotin, RU — kirill)

// Narx 160×200 uchun beriladi, qolgan o'lchamlar koeffitsient bilan hisoblanadi
export const SIZES = [
  { id: "80x190", f: 0.55 },
  { id: "90x200", f: 0.62 },
  { id: "120x200", f: 0.8 },
  { id: "140x200", f: 0.9 },
  { id: "160x200", f: 1 },
  { id: "180x200", f: 1.12 },
  { id: "200x200", f: 1.25 },
];

// model.kind: modular | classic | korpacha | topper
// model.anim: zones | explode | incline | fold | land
export const PRODUCTS = [
  { id: "mohir-20", name: "Mohir 2.0", type: "modular", firm: [1, 3], h: 26, price: 17400000, disc: 10, badge: "hit",
    load: 140, zones: "3", schemes: "5", warranty: 10, trial: 100,
    model: { kind: "modular", core: 0.15, band: "ikat", quilt: "diamond", zones: [1, 3, 2], anim: "zones" } },
  { id: "sokin-10", name: "Sokin 1.0", type: "modular", firm: [1, 2], h: 23, price: 12900000, disc: 10, badge: "lux",
    load: 110, zones: "3", schemes: "3", warranty: 10, trial: 100,
    model: { kind: "modular", core: 0.12, band: "ikat", quilt: "wave", zones: [1, 2, 1], anim: "explode" } },
  { id: "choqqi-30", name: "Cho‘qqi 3.0", type: "modular", firm: [1, 3], h: 30, price: 29900000, disc: 10, badge: "couple",
    load: 160, zones: "3 × 2", schemes: "5 + 5", warranty: 12, trial: 100,
    model: { kind: "modular", core: 0.18, tiers: 2, rows: 2, band: "gold", quilt: "diamond", zones: [2, 3, 2], anim: "explode" } },
  { id: "korpacha-air", name: "Ko‘rpacha Air", type: "korpacha", firm: [2, 2], h: 8, price: 3900000, disc: 0, badge: "local",
    load: 110, zones: "—", schemes: "—", warranty: 5, trial: 100, maxSize: "140x200",
    model: { kind: "korpacha", anim: "fold" } },
  { id: "tong-20", name: "Tong 20", type: "classic", firm: [2, 2], h: 20, price: 8400000, disc: 20, badge: "value",
    load: 110, zones: "—", schemes: "—", warranty: 7, trial: 100,
    model: { kind: "classic", core: 0.14, band: "knit", quilt: "grid", anim: "explode" } },
  { id: "mohir-21", name: "Mohir 2.1", type: "modular", firm: [1, 3], h: 26, price: 18900000, disc: 0, badge: "new",
    load: 140, zones: "3", schemes: "5", warranty: 10, trial: 100,
    model: { kind: "modular", core: 0.15, band: "ikat", quilt: "diamond", zones: [2, 2, 2], slices: 3, anim: "incline" } },
  { id: "tong-pro", name: "Tong Pro 28", type: "classic", firm: [3, 3], h: 28, price: 11200000, disc: 20, badge: null,
    load: 160, zones: "—", schemes: "—", warranty: 10, trial: 100,
    model: { kind: "classic", core: 0.2, tiers: 2, band: "knit", quilt: "grid", anim: "explode" } },
  { id: "topper-lux", name: "Topper Lyuks", type: "topper", firm: [1, 1], h: 6, price: 4600000, disc: 10, badge: null,
    load: 120, zones: "—", schemes: "—", warranty: 3, trial: 30,
    model: { kind: "topper", layers: 2, anim: "explode" } },
  { id: "topper-yol", name: "Yo‘l topper", type: "topper", firm: [2, 2], h: 4, price: 3400000, disc: 10, badge: null,
    load: 120, zones: "—", schemes: "—", warranty: 3, trial: 30,
    model: { kind: "topper", layers: 1, anim: "land" } },
];

export const COMPARE_IDS = ["sokin-10", "mohir-20", "choqqi-30", "tong-20", "tong-pro"];

export const PRESETS = [
  { id: "132", z: [1, 3, 2] },
  { id: "232", z: [2, 3, 2] },
  { id: "121", z: [1, 2, 1] },
  { id: "222", z: [2, 2, 2] },
  { id: "122", z: [1, 2, 2] },
];

export const T = {
  uz: {
    "meta.title": "Tayanch — matraslar katalogi",
    "promo.1": "100 kecha bepul sinab ko‘ring",
    "promo.2": "Toshkent bo‘ylab bepul yetkazib berish",
    "promo.3": "0% muddatli to‘lov — 12 oygacha",
    "promo.4": "10 yil kafolat",
    "nav.catalog": "Katalog",
    "nav.zones": "Zonalar",
    "nav.compare": "Solishtirish",
    "nav.service": "Xizmatlar",
    "nav.faq": "Savollar",
    "nav.cart": "Savat",
    "nav.menu": "Menyu",
    "nav.lang": "Tilni tanlang",

    "hero.eyebrow": "Matraslar katalogi · 2026",
    "hero.title": "Qattiqlikni o‘zingiz tanlang",
    "hero.lead": "Uch zonali modulli matraslar: yelka, bel va oyoqlar uchun alohida tayanch. G‘ilofi yuviladi, ichidan havo o‘tadi.",
    "hero.cta1": "Katalogni ko‘rish",
    "hero.cta2": "Zonalarni sozlash",
    "hero.f1n": "100 kecha", "hero.f1": "sinov muddati",
    "hero.f2n": "10 yil", "hero.f2": "kafolat",
    "hero.f3n": "3 zona", "hero.f3": "har biri o‘z qattiqligida",
    "hero.hint": "Pastga suring — matrasni qatlamlarga ajratamiz",

    "ch.0": "Matras", "ch.1": "Qatlamlar", "ch.2": "Zonalar", "ch.3": "Havo",

    "layers.kicker": "Ichida nima bor",
    "layers.title": "To‘rt qatlam, bitta vazifa — tinch uyqu",
    "layers.text": "Har bir qatlamni alohida chiqarib, tozalab yoki almashtirish mumkin. Qatlamlar yelimlanmagan, shuning uchun matras uzoq xizmat qiladi.",
    "l.cover": "Yuviladigan g‘ilof", "l.cover.s": "40 °C da yuviladi",
    "l.comfort": "Sovutuvchi qatlam", "l.comfort.s": "3D to‘r · 3 sm",
    "l.core": "Havo tolali bloklar", "l.core.s": "3 zona · 15 sm",
    "l.base": "Sirpanmaydigan asos", "l.base.s": "zich tola · 2 sm",

    "zones.kicker": "Uch zona",
    "zones.title": "Yelka, bel va oyoq — har biriga o‘z qattiqligi",
    "zones.text": "Bloklar ikki tomonli: bir tomoni yumshoqroq, ikkinchisi qattiqroq. Ularning joyini almashtirib, matrasni tanangizga moslaysiz — yangisini sotib olmasdan.",
    "firm.1": "Yumshoq", "firm.2": "O‘rta", "firm.3": "Qattiq",

    "air.kicker": "Havo va gigiyena",
    "air.title": "Tola orasidan havo o‘tadi — issiq kechada ham salqin",
    "air.text": "Toshkent yozida ko‘pikli matras issiqni ushlab qoladi. Havo tolasi esa issiqlik va namlikni tashqariga chiqaradi.",
    "air.f1n": "40 °C", "air.f1": "g‘ilof kir yuvish mashinasida yuviladi",
    "air.f2n": "Dush", "air.f2": "bloklarni suv bilan chayish mumkin",
    "air.f3n": "3 oy", "air.f3": "shu muddatda bloklarni aylantirib qo‘ying",

    "cat.kicker": "Katalog",
    "cat.title": "Matraslar, ko‘rpachalar va topperlar",
    "cat.text": "O‘lchamni tanlang — narxlar darhol yangilanadi. Kursorni kartaga olib boring: matras qatlamlarini ko‘rsatadi.",
    "f.type": "Turi", "f.firm": "Qattiqlik", "f.size": "O‘lcham, sm", "f.sort": "Saralash",
    "t.all": "Hammasi", "t.modular": "Modulli", "t.classic": "Klassik", "t.korpacha": "Ko‘rpacha", "t.topper": "Topper",
    "fm.all": "Har qanday",
    "s.pop": "Mashhurlari", "s.asc": "Avval arzonlari", "s.desc": "Avval qimmatlari",
    "cat.count": "{n} ta mahsulot",
    "cat.empty": "Bu filtrlar bo‘yicha mahsulot topilmadi.",
    "cat.reset": "Filtrlarni tozalash",

    "badge.hit": "Eng mashhur", "badge.lux": "Hashamatli qulaylik", "badge.couple": "Juftliklar uchun",
    "badge.local": "Milliy an’ana", "badge.value": "Qulay narx", "badge.new": "Yangi",

    "cur": "so‘m",
    "card.h": "Balandligi",
    "card.inst": "oyiga {x} so‘mdan · 12 oy",
    "card.more": "Batafsil",
    "card.add": "Savatga",
    "card.added": "Savatda",
    "card.nosize": "Bu o‘lchamda yo‘q — {max} gacha",
    "unit.cm": "sm", "unit.kg": "kg", "unit.y": "yil", "unit.n": "kecha",

    "p.mohir-20.tag": "Qattiqlik zonalar bo‘yicha sozlanadi",
    "p.mohir-20.desc": "Uchta ikki tomonli blok: 1-3-2 dan 2-2-2 gacha besh xil sxema. Oilalar eng ko‘p tanlaydigan model.",
    "p.mohir-20.core": "Havo tolasi, 3 zona",
    "p.sokin-10.tag": "Bosimni yumshatadi va salqin saqlaydi",
    "p.sokin-10.desc": "Yumshoq ustki qatlam yelka va sondagi bosimni kamaytiradi. Yonboshlab yotadiganlar uchun.",
    "p.sokin-10.core": "Havo tolasi, 3 zona, yumshoq qatlam",
    "p.choqqi-30.tag": "Eng ko‘p sozlanadigan matras",
    "p.choqqi-30.desc": "Ikki qavat blok, har yarmida uchtadan modul. Har bir yarmini alohida sozlang — juftliklar uchun qulay.",
    "p.choqqi-30.core": "Havo tolasi, 2 qavat, 12 modul",
    "p.korpacha-air.tag": "Yig‘iladigan zamonaviy ko‘rpacha",
    "p.korpacha-air.desc": "Uch bo‘lakka buklanadi va shkafga sig‘adi. Mehmon kelsa, joy bir daqiqada tayyor. G‘ilofi — adras naqshli.",
    "p.korpacha-air.core": "Havo tolasi, 3 bo‘lak",
    "p.tong-20.tag": "Birinchi xarid uchun ishonchli matras",
    "p.tong-20.desc": "20 sm havo tolasi va yuviladigan g‘ilof. Mehmonxona va ijaraga beriladigan uylar uchun ham mos.",
    "p.tong-20.core": "Havo tolasi, yaxlit blok",
    "p.mohir-21.tag": "Bosh qismi ko‘tariladigan karavotlar uchun",
    "p.mohir-21.desc": "Egiluvchan asos karavotning bosh qismi ko‘tarilganda ham bloklarni joyida ushlab turadi.",
    "p.mohir-21.core": "Havo tolasi, 3 zona, egiluvchan asos",
    "p.tong-pro.tag": "Qalinroq va qattiqroq tayanch",
    "p.tong-pro.desc": "Ikki qavatli yadro. Vazni og‘irroq bo‘lganlar va chalqancha yotadiganlar uchun.",
    "p.tong-pro.core": "Havo tolasi, 2 qavat",
    "p.topper-lux.tag": "Salqinlik va bosimdan xalos",
    "p.topper-lux.desc": "Ikki qatlamli topper: tepada yumshoq to‘r, pastda zich tola. Qattiq matrasni yumshatadi.",
    "p.topper-lux.core": "3D to‘r + havo tolasi",
    "p.topper-yol.tag": "Yengil, yuviladi, safarga olish oson",
    "p.topper-yol.desc": "4 sm havo tolasi eski matrasni qattiqroq va salqinroq qiladi. Rezinkalari bilan sirpanmaydi.",
    "p.topper-yol.core": "Havo tolasi, 4 sm",

    "cfg.kicker": "Zona konstruktori",
    "cfg.title": "Tanangizga mos sxemani yig‘ing",
    "cfg.text": "Tayyor sxemani tanlang yoki har bir zonani o‘zingiz sozlang. Raqam qancha katta bo‘lsa, blok shuncha qattiq.",
    "zone.0": "Yelka", "zone.1": "Bel", "zone.2": "Oyoq",
    "pr.132": "Beli og‘riydiganlar", "pr.132.d": "Yelkalar botadi, bel mustahkam ushlanadi, oyoqlar o‘rtacha tayanchda.",
    "pr.232": "Keng gavdalilar", "pr.232.d": "Og‘ir qismlar cho‘kib ketmaydi, umurtqa to‘g‘ri turadi.",
    "pr.121": "Ozg‘in gavdalilar", "pr.121.d": "Yengil tanaga yumshoq tayanch — bosim nuqtalari sezilmaydi.",
    "pr.222": "O‘rta gavdalilar", "pr.222.d": "Butun uzunlik bo‘yicha bir xil, muvozanatli tayanch.",
    "pr.122": "Yelkasi kenglar", "pr.122.d": "Yelkalar yumshoq botadi, bel va oyoqlar esa barqaror turadi.",
    "pr.custom": "Sizning sxemangiz", "pr.custom.d": "Zonalarni o‘zingiz sozladingiz. Bloklarni keyin ham almashtirsa bo‘ladi.",
    "cfg.presets": "Tayyor sxemalar",
    "cfg.manual": "Zonalarni qo‘lda sozlash",
    "cfg.scheme": "Sxema",
    "cfg.add": "Mohir 2.0 ni shu sxema bilan savatga qo‘shish",
    "cfg.set": "{zone}: {firm}",

    "cmp.kicker": "Solishtirish",
    "cmp.title": "Qaysi matras sizga to‘g‘ri keladi",
    "cmp.h": "Balandligi", "cmp.zones": "Zonalar", "cmp.firm": "Qattiqlik (1–3)", "cmp.schemes": "Sxemalar soni",
    "cmp.load": "Bir kishiga yuklama", "cmp.cover": "G‘ilof", "cmp.warranty": "Kafolat", "cmp.price": "Narxi, {size}",
    "cmp.washable": "yuviladi", "cmp.upto": "{n} kg gacha",

    "srv.kicker": "Xizmat",
    "srv.title": "Xarid qilishdan qo‘rqmang — avval sinab ko‘ring",
    "srv.1": "100 kecha sinov", "srv.1.d": "Matras yoqmasa, 100 kun ichida o‘zimiz olib ketamiz va pulni to‘liq qaytaramiz.",
    "srv.2": "Bepul yetkazib berish", "srv.2.d": "Toshkentda 24 soat ichida, viloyatlarga 3–5 kunda. Qavatga olib chiqib, o‘rnatib beramiz.",
    "srv.3": "0% muddatli to‘lov", "srv.3.d": "3, 6 yoki 12 oyga, ustamasiz. Pasport va bank kartasi yetarli.",
    "srv.4": "Eski matrasni olib ketamiz", "srv.4.d": "Yangisini olib kelganda eskisini bepul olib ketamiz va qayta ishlashga topshiramiz.",
    "srv.5": "10 yil kafolat", "srv.5.d": "Bloklar shaklini yo‘qotsa yoki cho‘kib qolsa, almashtirib beramiz.",
    "srv.6": "Showroomda yotib ko‘ring", "srv.6.d": "Har bir modelda 15 daqiqa yotib ko‘rsa bo‘ladi, maslahatchi zonalarni sozlab beradi.",
    "shw.title": "Showroomlar",
    "shw.hours": "Har kuni 10:00–21:00",
    "shw.1": "Toshkent, Yunusobod", "shw.1.a": "Amir Temur shoh ko‘chasi",
    "shw.2": "Toshkent, Chilonzor", "shw.2.a": "Bunyodkor shoh ko‘chasi",
    "shw.3": "Samarqand", "shw.3.a": "Universitet xiyoboni",

    "faq.kicker": "Savollar",
    "faq.title": "Ko‘p beriladigan savollar",
    "faq.1.q": "Havo tolasi nima va u ko‘pikdan nimasi bilan farq qiladi?",
    "faq.1.a": "Bu — bir-biriga chalkashtirib to‘qilgan polimer iplardan iborat elastik blok. Hajmining katta qismi havo, shuning uchun u issiqni ushlamaydi, shaklini tez tiklaydi va suv bilan yuviladi. Ko‘pik esa vaqt o‘tib cho‘kadi va namlikni o‘ziga tortadi.",
    "faq.2.q": "Qanday qattiqlik kerakligini bilmayman. Nima qilay?",
    "faq.2.a": "Modulli matras oling: bloklarning joyini almashtirib, sxemani uyda tanlaysiz. Yoki showroomga keling — maslahatchi 10 daqiqada mos variantni topib beradi.",
    "faq.3.q": "Har qanday holatda yotadiganlarga mos keladimi?",
    "faq.3.a": "Ha. Yonboshlab yotadiganlarga yelka zonasini yumshoqroq, chalqancha yoki qorni bilan yotadiganlarga bel zonasini qattiqroq qilishni tavsiya qilamiz.",
    "faq.4.q": "100 kecha sinov qanday ishlaydi?",
    "faq.4.a": "Matras yetkazilgan kundan boshlab 100 kun ichida qo‘ng‘iroq qiling: kuryer uni bepul olib ketadi, pul 5 ish kunida kartangizga qaytadi. Dastlabki 30 kecha — moslashish davri, bu vaqtda qaytarib bo‘lmaydi.",
    "faq.5.q": "Muddatli to‘lovni qanday rasmiylashtiraman?",
    "faq.5.a": "Savatda «Muddatli to‘lov»ni tanlang, pasport ma’lumotlari va karta raqamini kiriting. Qaror 5 daqiqada chiqadi, birinchi to‘lov — bir oydan keyin.",
    "faq.6.q": "Matrasni qanday parvarishlash kerak?",
    "faq.6.a": "G‘ilofni yechib, 40 °C da yuving. Bloklarni dush ostida chayib, soyada 1–2 kun quriting. Har 3 oyda bloklarni aylantirib qo‘ying — shunda ular bir tekis ishlaydi.",

    "lead.title": "Tanlashga yordam beramiz",
    "lead.text": "Raqamingizni qoldiring. Uyqu maslahatchisi 15 daqiqa ichida qo‘ng‘iroq qilib, bo‘yingiz, vazningiz va qanday yotishingizga qarab matras tavsiya qiladi.",
    "lead.name": "Ismingiz", "lead.phone": "Telefon raqamingiz",
    "lead.submit": "Qo‘ng‘iroqni kutaman",
    "lead.ok": "Rahmat! Maslahatchi tez orada qo‘ng‘iroq qiladi.",
    "lead.err": "Telefon raqamini to‘liq kiriting: +998 va 9 ta raqam.",
    "lead.errName": "Ismingizni yozing — maslahatchi sizga qanday murojaat qilishni bilsin.",

    "cart.title": "Savat",
    "cart.empty": "Savat hozircha bo‘sh. Katalogdan matras tanlang.",
    "cart.toCatalog": "Katalogga o‘tish",
    "cart.total": "Jami",
    "cart.delivery": "Yetkazib berish", "cart.free": "bepul",
    "cart.inst": "Muddatli to‘lovda: oyiga {x} so‘m · 12 oy",
    "cart.checkout": "Buyurtma berish",
    "cart.remove": "Olib tashlash",
    "cart.less": "Kamaytirish", "cart.more": "Ko‘paytirish",
    "cart.pay": "To‘lov: Click, Payme, Uzcard, Humo, Visa yoki muddatli to‘lov",
    "cart.close": "Savatni yopish",
    "toast.added": "{name} savatga qo‘shildi",
    "toast.order": "Buyurtma qabul qilindi. Operator 15 daqiqa ichida bog‘lanadi.",

    "m.close": "Yopish",
    "m.explode": "Qatlamlarga ajratish",
    "m.fold": "Buklash",
    "m.lift": "Matrasdan ko‘tarish",
    "m.drag": "Aylantirish uchun suring",
    "m.size": "O‘lcham",
    "m.inst": "Muddatli to‘lov",
    "m.months": "{n} oy",
    "m.perMonth": "oyiga {x} so‘m",
    "m.core": "Ichki qismi",
    "m.cover": "G‘ilof", "m.coverV": "olinadi, 40 °C da yuviladi",
    "m.load": "Bir kishiga yuklama",
    "m.warranty": "Kafolat",
    "m.trial": "Sinov muddati",

    "foot.about": "Tayanch — Toshkentdagi uyqu do‘koni. Matraslarni o‘zimiz sinaymiz, o‘zimiz yetkazamiz va o‘rnatamiz.",
    "foot.c1": "Katalog", "foot.c2": "Xaridorlarga", "foot.c3": "Aloqa",
    "foot.l.mattr": "Matraslar", "foot.l.korp": "Ko‘rpachalar", "foot.l.top": "Topperlar", "foot.l.zones": "Zona konstruktori",
    "foot.l.deliv": "Yetkazib berish", "foot.l.inst": "Muddatli to‘lov", "foot.l.ret": "Qaytarish", "foot.l.war": "Kafolat",
    "foot.tg": "Telegram orqali yozish",
    "foot.copy": "© 2026 Tayanch. Dizayn konsepti.",
  },

  ru: {
    "meta.title": "Таянч — каталог матрасов",
    "promo.1": "100 ночей бесплатного теста",
    "promo.2": "Бесплатная доставка по Ташкенту",
    "promo.3": "Рассрочка 0% — до 12 месяцев",
    "promo.4": "Гарантия 10 лет",
    "nav.catalog": "Каталог",
    "nav.zones": "Зоны",
    "nav.compare": "Сравнение",
    "nav.service": "Сервис",
    "nav.faq": "Вопросы",
    "nav.cart": "Корзина",
    "nav.menu": "Меню",
    "nav.lang": "Выберите язык",

    "hero.eyebrow": "Каталог матрасов · 2026",
    "hero.title": "Жёсткость — на ваш выбор",
    "hero.lead": "Модульные матрасы с тремя зонами: отдельная поддержка для плеч, поясницы и ног. Чехол стирается, наполнитель пропускает воздух.",
    "hero.cta1": "Смотреть каталог",
    "hero.cta2": "Настроить зоны",
    "hero.f1n": "100 ночей", "hero.f1": "на пробу",
    "hero.f2n": "10 лет", "hero.f2": "гарантия",
    "hero.f3n": "3 зоны", "hero.f3": "у каждой своя жёсткость",
    "hero.hint": "Листайте вниз — разберём матрас по слоям",

    "ch.0": "Матрас", "ch.1": "Слои", "ch.2": "Зоны", "ch.3": "Воздух",

    "layers.kicker": "Что внутри",
    "layers.title": "Четыре слоя ради одного — спокойного сна",
    "layers.text": "Каждый слой можно вынуть, почистить или заменить. Слои не склеены, поэтому матрас служит дольше.",
    "l.cover": "Съёмный чехол", "l.cover.s": "стирка при 40 °C",
    "l.comfort": "Охлаждающий слой", "l.comfort.s": "3D-сетка · 3 см",
    "l.core": "Блоки из воздушного волокна", "l.core.s": "3 зоны · 15 см",
    "l.base": "Нескользящее основание", "l.base.s": "плотное волокно · 2 см",

    "zones.kicker": "Три зоны",
    "zones.title": "Плечи, поясница, ноги — у каждой зоны своя жёсткость",
    "zones.text": "Блоки двусторонние: одна сторона мягче, другая твёрже. Меняя их местами, вы подстраиваете матрас под себя — без покупки нового.",
    "firm.1": "Мягкая", "firm.2": "Средняя", "firm.3": "Жёсткая",

    "air.kicker": "Воздух и гигиена",
    "air.title": "Воздух проходит сквозь волокно — прохладно даже жаркой ночью",
    "air.text": "Летом в Ташкенте поролон держит тепло. Воздушное волокно отводит жар и влагу наружу.",
    "air.f1n": "40 °C", "air.f1": "чехол стирается в машинке",
    "air.f2n": "Душ", "air.f2": "блоки можно промыть водой",
    "air.f3n": "3 мес.", "air.f3": "с такой периодичностью переворачивайте блоки",

    "cat.kicker": "Каталог",
    "cat.title": "Матрасы, курпачи и топперы",
    "cat.text": "Выберите размер — цены обновятся сразу. Наведите курсор на карточку, и матрас покажет свои слои.",
    "f.type": "Тип", "f.firm": "Жёсткость", "f.size": "Размер, см", "f.sort": "Сортировка",
    "t.all": "Все", "t.modular": "Модульные", "t.classic": "Классические", "t.korpacha": "Курпачи", "t.topper": "Топперы",
    "fm.all": "Любая",
    "s.pop": "Популярные", "s.asc": "Сначала дешевле", "s.desc": "Сначала дороже",
    "cat.count": "{n} {товар|товара|товаров}",
    "cat.empty": "По этим фильтрам ничего не нашлось.",
    "cat.reset": "Сбросить фильтры",

    "badge.hit": "Хит продаж", "badge.lux": "Премиальный комфорт", "badge.couple": "Для пары",
    "badge.local": "Национальная традиция", "badge.value": "Выгодная цена", "badge.new": "Новинка",

    "cur": "сум",
    "card.h": "Высота",
    "card.inst": "от {x} сум/мес · 12 мес.",
    "card.more": "Подробнее",
    "card.add": "В корзину",
    "card.added": "В корзине",
    "card.nosize": "Нет в этом размере — до {max}",
    "unit.cm": "см", "unit.kg": "кг", "unit.y": "лет", "unit.n": "ночей",

    "p.mohir-20.tag": "Жёсткость настраивается по зонам",
    "p.mohir-20.desc": "Три двусторонних блока: пять схем — от 1-3-2 до 2-2-2. Самая популярная модель у семей.",
    "p.mohir-20.core": "Воздушное волокно, 3 зоны",
    "p.sokin-10.tag": "Снимает давление и сохраняет прохладу",
    "p.sokin-10.desc": "Мягкий верхний слой снижает давление на плечи и бёдра. Для тех, кто спит на боку.",
    "p.sokin-10.core": "Воздушное волокно, 3 зоны, мягкий слой",
    "p.choqqi-30.tag": "Самый настраиваемый матрас",
    "p.choqqi-30.desc": "Два яруса блоков, в каждой половине по три модуля. Каждую половину можно настроить отдельно — удобно для пары.",
    "p.choqqi-30.core": "Воздушное волокно, 2 яруса, 12 модулей",
    "p.korpacha-air.tag": "Складная курпача нового поколения",
    "p.korpacha-air.desc": "Складывается втрое и помещается в шкаф. Пришли гости — спальное место готово за минуту. Чехол — с узором адрас.",
    "p.korpacha-air.core": "Воздушное волокно, 3 секции",
    "p.tong-20.tag": "Надёжный матрас для первой покупки",
    "p.tong-20.desc": "20 см воздушного волокна и стираемый чехол. Подходит для гостевой комнаты и квартиры под аренду.",
    "p.tong-20.core": "Воздушное волокно, цельный блок",
    "p.mohir-21.tag": "Для кроватей с подъёмным изголовьем",
    "p.mohir-21.desc": "Гибкое основание удерживает блоки на месте, даже когда изголовье кровати поднято.",
    "p.mohir-21.core": "Воздушное волокно, 3 зоны, гибкое основание",
    "p.tong-pro.tag": "Толще и твёрже",
    "p.tong-pro.desc": "Двухъярусное ядро. Для людей с большим весом и тех, кто спит на спине.",
    "p.tong-pro.core": "Воздушное волокно, 2 яруса",
    "p.topper-lux.tag": "Прохлада и снятие давления",
    "p.topper-lux.desc": "Двухслойный топпер: сверху мягкая сетка, снизу плотное волокно. Смягчает слишком жёсткий матрас.",
    "p.topper-lux.core": "3D-сетка + воздушное волокно",
    "p.topper-yol.tag": "Лёгкий, стирается, удобно брать в поездку",
    "p.topper-yol.desc": "4 см воздушного волокна делают старый матрас твёрже и прохладнее. Резинки не дают ему съезжать.",
    "p.topper-yol.core": "Воздушное волокно, 4 см",

    "cfg.kicker": "Конструктор зон",
    "cfg.title": "Соберите схему под своё тело",
    "cfg.text": "Выберите готовую схему или настройте каждую зону сами. Чем больше цифра, тем твёрже блок.",
    "zone.0": "Плечи", "zone.1": "Поясница", "zone.2": "Ноги",
    "pr.132": "Если болит спина", "pr.132.d": "Плечи погружаются, поясница надёжно поддержана, ноги — на средней опоре.",
    "pr.232": "Крупное телосложение", "pr.232.d": "Тяжёлые зоны не проваливаются, позвоночник остаётся ровным.",
    "pr.121": "Худощавое телосложение", "pr.121.d": "Мягкая поддержка для лёгкого тела — точки давления не ощущаются.",
    "pr.222": "Среднее телосложение", "pr.222.d": "Ровная сбалансированная поддержка по всей длине.",
    "pr.122": "Широкие плечи", "pr.122.d": "Плечам есть куда погрузиться, поясница и ноги лежат устойчиво.",
    "pr.custom": "Ваша схема", "pr.custom.d": "Вы настроили зоны сами. Блоки можно переставить и потом.",
    "cfg.presets": "Готовые схемы",
    "cfg.manual": "Настроить зоны вручную",
    "cfg.scheme": "Схема",
    "cfg.add": "Добавить Mohir 2.0 с этой схемой",
    "cfg.set": "{zone}: {firm}",

    "cmp.kicker": "Сравнение",
    "cmp.title": "Какой матрас подойдёт именно вам",
    "cmp.h": "Высота", "cmp.zones": "Зоны", "cmp.firm": "Жёсткость (1–3)", "cmp.schemes": "Схем настройки",
    "cmp.load": "Нагрузка на место", "cmp.cover": "Чехол", "cmp.warranty": "Гарантия", "cmp.price": "Цена, {size}",
    "cmp.washable": "стирается", "cmp.upto": "до {n} кг",

    "srv.kicker": "Сервис",
    "srv.title": "Не бойтесь покупать — сначала попробуйте",
    "srv.1": "100 ночей на пробу", "srv.1.d": "Если матрас не подошёл, в течение 100 дней сами заберём его и вернём деньги полностью.",
    "srv.2": "Бесплатная доставка", "srv.2.d": "По Ташкенту — за 24 часа, в регионы — за 3–5 дней. Поднимем на этаж и установим.",
    "srv.3": "Рассрочка 0%", "srv.3.d": "На 3, 6 или 12 месяцев без переплаты. Нужны только паспорт и банковская карта.",
    "srv.4": "Вывезем старый матрас", "srv.4.d": "Привезём новый — бесплатно заберём старый и сдадим на переработку.",
    "srv.5": "Гарантия 10 лет", "srv.5.d": "Если блоки потеряют форму или просядут, заменим их.",
    "srv.6": "Полежите в шоуруме", "srv.6.d": "На каждой модели можно полежать 15 минут, консультант настроит зоны.",
    "shw.title": "Шоурумы",
    "shw.hours": "Ежедневно 10:00–21:00",
    "shw.1": "Ташкент, Юнусабад", "shw.1.a": "проспект Амира Темура",
    "shw.2": "Ташкент, Чиланзар", "shw.2.a": "проспект Бунёдкор",
    "shw.3": "Самарканд", "shw.3.a": "Университетский бульвар",

    "faq.kicker": "Вопросы",
    "faq.title": "Частые вопросы",
    "faq.1.q": "Что такое воздушное волокно и чем оно отличается от поролона?",
    "faq.1.a": "Это упругий блок из переплетённых полимерных нитей. Большая часть его объёма — воздух, поэтому он не держит тепло, быстро восстанавливает форму и моется водой. Поролон со временем проседает и впитывает влагу.",
    "faq.2.q": "Не знаю, какая жёсткость мне нужна. Что делать?",
    "faq.2.a": "Берите модульный матрас: переставляя блоки, вы подберёте схему прямо дома. Или приходите в шоурум — консультант подберёт вариант за 10 минут.",
    "faq.3.q": "Подходит ли матрас для любой позы сна?",
    "faq.3.a": "Да. Тем, кто спит на боку, советуем сделать мягче зону плеч; тем, кто спит на спине или животе, — твёрже зону поясницы.",
    "faq.4.q": "Как работают 100 ночей на пробу?",
    "faq.4.a": "Позвоните в течение 100 дней с момента доставки: курьер бесплатно заберёт матрас, деньги вернутся на карту за 5 рабочих дней. Первые 30 ночей — период привыкания, в это время возврат не оформляется.",
    "faq.5.q": "Как оформить рассрочку?",
    "faq.5.a": "В корзине выберите «Рассрочка», укажите паспортные данные и номер карты. Решение — за 5 минут, первый платёж — через месяц.",
    "faq.6.q": "Как ухаживать за матрасом?",
    "faq.6.a": "Снимите чехол и постирайте при 40 °C. Блоки промойте под душем и высушите в тени 1–2 дня. Раз в 3 месяца переворачивайте блоки — так они изнашиваются равномерно.",

    "lead.title": "Поможем с выбором",
    "lead.text": "Оставьте номер. Консультант по сну перезвонит в течение 15 минут и подберёт матрас по росту, весу и позе сна.",
    "lead.name": "Ваше имя", "lead.phone": "Номер телефона",
    "lead.submit": "Жду звонка",
    "lead.ok": "Спасибо! Консультант скоро перезвонит.",
    "lead.err": "Введите номер полностью: +998 и 9 цифр.",
    "lead.errName": "Напишите имя — консультанту нужно знать, как к вам обращаться.",

    "cart.title": "Корзина",
    "cart.empty": "Корзина пока пуста. Выберите матрас в каталоге.",
    "cart.toCatalog": "Перейти в каталог",
    "cart.total": "Итого",
    "cart.delivery": "Доставка", "cart.free": "бесплатно",
    "cart.inst": "В рассрочку: {x} сум/мес · 12 мес.",
    "cart.checkout": "Оформить заказ",
    "cart.remove": "Удалить",
    "cart.less": "Уменьшить", "cart.more": "Увеличить",
    "cart.pay": "Оплата: Click, Payme, Uzcard, Humo, Visa или рассрочка",
    "cart.close": "Закрыть корзину",
    "toast.added": "{name} — в корзине",
    "toast.order": "Заказ принят. Оператор свяжется в течение 15 минут.",

    "m.close": "Закрыть",
    "m.explode": "Разобрать по слоям",
    "m.fold": "Сложить",
    "m.lift": "Поднять над матрасом",
    "m.drag": "Потяните, чтобы повернуть",
    "m.size": "Размер",
    "m.inst": "Рассрочка",
    "m.months": "{n} мес.",
    "m.perMonth": "{x} сум в месяц",
    "m.core": "Наполнение",
    "m.cover": "Чехол", "m.coverV": "съёмный, стирка при 40 °C",
    "m.load": "Нагрузка на место",
    "m.warranty": "Гарантия",
    "m.trial": "Пробный период",

    "foot.about": "Таянч — магазин сна в Ташкенте. Сами тестируем матрасы, сами доставляем и устанавливаем.",
    "foot.c1": "Каталог", "foot.c2": "Покупателям", "foot.c3": "Контакты",
    "foot.l.mattr": "Матрасы", "foot.l.korp": "Курпачи", "foot.l.top": "Топперы", "foot.l.zones": "Конструктор зон",
    "foot.l.deliv": "Доставка", "foot.l.inst": "Рассрочка", "foot.l.ret": "Возврат", "foot.l.war": "Гарантия",
    "foot.tg": "Написать в Telegram",
    "foot.copy": "© 2026 Таянч. Дизайн-концепт.",
  },
};
